// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKtIHgcsVgjayUTXaBjCo9TtUVwDF2fkc',
    appId: '1:479695283627:web:8d4cbb7e4d4c5c3978deee',
    messagingSenderId: '479695283627',
    projectId: 'score-49de5',
    authDomain: 'score-49de5.firebaseapp.com',
    storageBucket: 'score-49de5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmBlymBTmQNIrS-D5X84P1Qi2HH9xHzrk',
    appId: '1:479695283627:android:4d6a18a8e705bd6478deee',
    messagingSenderId: '479695283627',
    projectId: 'score-49de5',
    storageBucket: 'score-49de5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATHijPFxF3SQBEP9QpB3gJOP7e14Ed6xU',
    appId: '1:479695283627:ios:d5dc7782b91f94be78deee',
    messagingSenderId: '479695283627',
    projectId: 'score-49de5',
    storageBucket: 'score-49de5.appspot.com',
    iosClientId: '479695283627-5ek96t7cduivvgliqeereu0vmpm9gppp.apps.googleusercontent.com',
    iosBundleId: 'com.example.fourscore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATHijPFxF3SQBEP9QpB3gJOP7e14Ed6xU',
    appId: '1:479695283627:ios:5ca6a54d1f939fbb78deee',
    messagingSenderId: '479695283627',
    projectId: 'score-49de5',
    storageBucket: 'score-49de5.appspot.com',
    iosClientId: '479695283627-ql77m8182g2ilpk9f1qbcl3heiodr5an.apps.googleusercontent.com',
    iosBundleId: 'com.example.fourscore.RunnerTests',
  );
}
